title = input("Введите заголовок заметки: ")
print (title)
created_date = input ('Введите дату начала в формате 01-01-2000: ')
print (created_date[0:5])
issue_date = input ('Введите дату окончания в формате 01-01-2000: ')
print(issue_date[0:5])